# Dependencies

In [59]:
import torch
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

# Dataset

In [60]:
MASK_RATIO = 0.25

In [61]:
movies = pd.read_csv('ml-1m/movies.dat',sep='::',header=None,names=["MovieID", "Title", "Genres"],engine='python')
ratings = pd.read_csv('ml-1m/ratings.dat',sep='::',header=None,names=["UserID", "MovieID", "Rating", "Timestamp"],engine='python')
users = pd.read_csv('ml-1m/users.dat',sep='::',header=None,names=["UserID", "Gender", "Age", "Occupation", "Zip-code"],engine='python')

In [62]:
movies.head()

MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [63]:
users.head()

UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [64]:
ratings.head()

UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [65]:
movies.shape, ratings.shape, users.shape

((3883, 3), (1000209, 4), (6040, 5))

In [66]:
ratings.groupby('UserID').count()[["MovieID"]].sort_values(by="MovieID")

MovieID
UserID         
947          20
4068         20
2530         20
341          20
5258         20
...         ...
1181       1521
1941       1595
4277       1743
1680       1850
4169       2314

[6040 rows x 1 columns]

In [67]:
ratings.groupby('MovieID').count()[["UserID"]].sort_values(by="UserID")

UserID
MovieID        
402           1
2214          1
3382          1
2217          1
2218          1
...         ...
480        2672
1210       2883
1196       2990
260        2991
2858       3428

[3706 rows x 1 columns]

In [68]:
USERS_CNT = 6040

In [132]:
train_ratings, test_ratings = train_test_split(ratings, test_size=0.1)

In [69]:
def generate_sparse_matrix(dataset):
    items_max_id = dataset.MovieID.max()
    print(items_max_id)

    items = np.zeros(shape = (items_max_id, USERS_CNT), dtype = np.float32)

    for index, row in dataset.iterrows():
        items[int(row['MovieID'] - 1), int(row['UserID'] - 1)] = row['Rating']

    return items

In [133]:
train_ratings = generate_sparse_matrix(train_ratings) 
test_ratings = generate_sparse_matrix(test_ratings) 

3952
3952


In [134]:
train_ratings.shape, test_ratings.shape

((3952, 6040), (3952, 6040))

In [136]:
from torch.utils.data import Dataset

class RatingsDataset(Dataset):
    
    def __init__(self, ratings):
        self.ratings = ratings.copy()
        self.known_indices = self.get_known_indices()
       # self.normalize()
       # self.subtract_mean()
        
        self.masked_ratings, self.masked_indices = self.mask_ratings()
        
        
    def __len__(self):
        return len(self.ratings)
    
    def __getitem__(self, index):
        
        result = {
            'inp': torch.from_numpy(np.array(self.masked_ratings[index])).float(), 
            'out': torch.from_numpy(np.array(self.ratings[index])).float(),
            'known_indices': self.known_indices[index],
            'masked_indices': self.masked_indices[index]
        }
        
        return result
        
    
    def get_known_indices(self):
        known_indices = np.zeros(shape = self.ratings.shape)

        for index, rating in enumerate(self.ratings):
            known = np.where(rating > 0)[0].tolist()
            known_indices[index][known] = 1
            
        return known_indices
        
    def mask_ratings(self):
    
        masked_ratings = self.ratings.copy()
        masked_indices = np.zeros(shape = self.ratings.shape)
                
        for index, rating in enumerate(masked_ratings):
            
            known = np.where(self.known_indices[index] == 1)[0].tolist()
            known_cnt = len(known)
            masked_features_cnt = int(MASK_RATIO * known_cnt)
            masked = random.sample(known, masked_features_cnt)
            rating[masked] = 0
                        
            masked_indices[index][masked] = 1
            
            
        return masked_ratings, masked_indices
    
#     def normalize(self):
        
#         for index, rating in enumerate(self.ratings):
#             known = np.where(self.known_indices[index] == 1)[0]
            
#             if len(known) > 0:
#                 min_rating = rating[known].min()
#                 max_rating = rating[known].max()
#                 average_rating = (max_rating + min_rating) / 2
#                 range_rating = (max_rating - min_rating) / 2
#                 print(range_rating)
#                 rating[known] -= average_rating
#                 rating[known] /= range_rating
    
    def normalize(self):
        
        for index, rating in enumerate(self.ratings):
            known = np.where(self.known_indices[index] == 1)[0]
            
            if len(known) > 0:
                rating[known] -= 3
                rating[known] /= 2
    
    def subtract_mean(self):
        
        for index, rating in enumerate(self.ratings):
            
            known = np.where(self.known_indices[index] == 1)[0]
            
            if len(known) > 0:
                mean = rating[known].mean()
                rating[known] -= mean


In [137]:
train_dataset = RatingsDataset(train_ratings)

In [138]:
test_dataset = RatingsDataset(test_ratings)

In [139]:
print(train_dataset[0])

{'inp': tensor([0., 0., 0.,  ..., 0., 0., 3.]), 'out': tensor([5., 0., 0.,  ..., 0., 0., 3.]), 'known_indices': array([1., 0., 0., ..., 0., 0., 1.]), 'masked_indices': array([1., 0., 0., ..., 0., 0., 0.])}


# Network

In [141]:
def init_weights(m):
    if type(m) == nn.Linear:
        torch.nn.init.xavier_uniform_(m.weight)
        m.bias.data.fill_(0.01)

In [142]:
import torch.nn as nn
import sparselinear as sl


inputSize = 6040
class Denoising_Model(nn.Module):
    def __init__(self):
        super(Denoising_Model,self).__init__()
        self.encoder = nn.Sequential(nn.Linear(inputSize, 256), 
                                     nn.Sigmoid(), nn.Linear(256, 128), 
                                     nn.Sigmoid())
         self.decoder = nn.Sequential(
                                     nn.Linear(128, 256),
                                     nn.Sigmoid(),
                                     nn.Linear(256, inputSize))


    def forward(self,x):
        x=self.encoder(x)
        x=self.decoder(x)
        return x
    
network = Denoising_Model()
print(network)

Denoising_Model(
  (encoder): Sequential(
    (0): Linear(in_features=6040, out_features=256, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=128, out_features=256, bias=True)
    (5): Sigmoid()
    (6): Linear(in_features=256, out_features=6040, bias=True)
  )
)


In [143]:
print(len(train_dataset))

3952


In [128]:
ALPHA = 1
BETA = 0.5

In [129]:
from torch.autograd import Variable

class DenoisingLoss(nn.Module):
    
    def __init__(self, alpha=1, beta=0.5):
      super().__init__()
      self.alpha = alpha
      self.beta = beta
    
    def forward(self, output, target, known, masked):

        loss = 0

        for index, out in enumerate(output):
            out = output[index]

            known_indices = np.where(known[index] == 1)[0]
            masked_indices = np.where(masked[index] == 1)[0]
            known_masked_diff = list(set(known_indices) - set(masked_indices))        

            masked_output = Variable(output[index][masked_indices], requires_grad=True)
            masked_target = Variable(target[index][masked_indices] , requires_grad=True)
            known_masked_diff_output = Variable(output[index][known_masked_diff], requires_grad=True)
            known_masked_diff_target = Variable(target[index][known_masked_diff], requires_grad=True)

            #print(masked_output)
           # print(masked_target)
            if len(masked_output) > 0 and len(known_masked_diff_output) > 0:
                loss += ALPHA*torch.sum((masked_output - masked_target)**2) \
                        + BETA*torch.sum((known_masked_diff_output - known_masked_diff_target)**2)

        return loss / BATCH_SIZE


In [191]:
def MSEloss(predictions, target, known):
    
    cnt_known = 0
    
    for i, kn in enumerate(known):
        
        unknown_idx = np.where(known[i] == 0)[0]
        predictions[i][unknown_idx] = 0
        print(predictions[i])
        cnt_known += len(np.where(known[i] == 1)[0])
        
    print(cnt_known)
    loss = torch.div(torch.sum(torch.square(torch.sub(predictions, target))), cnt_known)
    
    return loss       
    


In [192]:
def train(model, inp, target, optimizer, known, masked, criterion):   
   # masked_ratings,known_ratings=masked_ratings.to(device),known_ratings.to(device)

    # Forward Pass
    output = model(inp)
    loss = MSEloss(output, target, known)    

    #Backward Pass---------------------
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    return loss, output


In [194]:
from torch.optim import Adam
from torch.utils.data import DataLoader
from tqdm import tqdm
from torch import optim
from torch.utils.data import DataLoader

if torch.cuda.is_available()==True:
    device="cuda:0"
else:
    device ="cpu"
    
criterion = nn.MSELoss()
#criterion=DenoisingLoss(ALPHA, BETA)
EPOCHS = 20
BATCH_SIZE = 28

train_loader = DataLoader(dataset = train_dataset, batch_size = BATCH_SIZE, shuffle = True)
model=Denoising_Model().to(device)
init_weights(model)
optimizer=optim.Adam(model.parameters(),lr=0.07,weight_decay=0.05)

epoch_loss=0
for epoch in range(EPOCHS):       
    for bidx, batch in enumerate(train_loader):
       
        x_train = batch['out']
        y_train = batch['out']
        known = batch['known_indices']
        masked = batch['masked_indices']
        loss, predictions = train(network, x_train, y_train, optimizer, known, masked, criterion)
        epoch_loss += loss
        
    print('Epoch {} Loss : {}'.format((epoch+1),loss))



tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2802],
       grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2801],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0.

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2799],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackw

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3426,  0.2816],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<Selec

tensor([0.0000, 0.0000, 0.5729,  ..., 0.0000, 0.0000, 0.0000],
       grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2788],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000, -0.0188,  0.0000,  ...,  0.0000,  0.0000,  0.2803],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBa

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.3677, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3399,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  .

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2806],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2804],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
5460
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000, -0.0192,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.2569, -0.3420,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0.0000, 

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
4459
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2809],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2793],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..

tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3407,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.2600, 0.0000, 0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
6259
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000, -0.0173,  0.0000,  ...,  0.0000,  0.0000,  0.2773],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_f

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000, -0.0191,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3426,  0.2819],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.3644,  0.0000,  0.5751,  ...,  0.0000, -0.3392,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3437,  0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2804],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<Se

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ...,

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2796],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.3686, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2774],
       grad_fn=<SelectBackward>)
tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2792],

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt


def test():
    criterion=nn.MSELoss()
    noRatings = 0
    input, target, minibatch = {}, {}, {}
    # TODO: Replace 'out'/'inp' 
    y_true = [test_dataset[i]['out'] for i in range(len(test_dataset))]
    y_pred = []

    test_loader = DataLoader(dataset = test_dataset, batch_size = BATCH_SIZE, shuffle = False)
    for bidx, batch in enumerate(test_loader):
            x_train = batch['inp']
            y_pred.append(model(x_train))

    y_pred = [x.item() for i in range(len(y_pred)) for x in y_pred[i] ]

    rmse = sqrt(mean_squared_error(y_true, y_pred))
    print("RMSE: ", rmse)

test()